2021-08-04 13:23:43.852 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:43.877 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 0.4554ms
2021-08-04 13:23:43.877 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:43.878 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:43.881 -03:00 [INF] Request finished in 29.3472ms 500 text/plain
2021-08-04 13:23:44.056 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/api/Clientes  
2021-08-04 13:23:44.056 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:44.057 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:44.058 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 1.5108ms
2021-08-04 13:23:44.059 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:44.059 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:44.062 -03:00 [INF] Request finished in 6.2748ms 500 text/plain
2021-08-04 13:23:44.289 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/api/Clientes  
2021-08-04 13:23:44.290 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:44.291 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:44.292 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 0.9755ms
2021-08-04 13:23:44.292 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:44.293 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:44.297 -03:00 [INF] Request finished in 8.7687ms 500 text/plain
2021-08-04 13:23:44.521 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/api/Clientes  
2021-08-04 13:23:44.521 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:44.521 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:44.521 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 0.2873ms
2021-08-04 13:23:44.521 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:44.522 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:44.526 -03:00 [INF] Request finished in 4.8949ms 500 text/plain
2021-08-04 13:23:44.735 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/api/Clientes  
2021-08-04 13:23:44.735 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:44.735 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:44.736 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 0.4683ms
2021-08-04 13:23:44.736 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:44.736 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:44.738 -03:00 [INF] Request finished in 3.5299ms 500 text/plain
2021-08-04 13:23:45.032 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/api/Clientes  
2021-08-04 13:23:45.032 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:45.033 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:45.034 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 0.962ms
2021-08-04 13:23:45.034 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:45.035 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:45.038 -03:00 [INF] Request finished in 6.3503ms 500 text/plain
2021-08-04 13:23:45.312 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/api/Clientes  
2021-08-04 13:23:45.312 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:45.313 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:45.314 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 0.7436ms
2021-08-04 13:23:45.314 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:45.314 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:45.317 -03:00 [INF] Request finished in 5.3177ms 500 text/plain
2021-08-04 13:23:45.551 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/api/Clientes  
2021-08-04 13:23:45.551 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:45.551 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:45.552 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 0.4099ms
2021-08-04 13:23:45.552 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:45.552 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:45.556 -03:00 [INF] Request finished in 4.8673ms 500 text/plain
2021-08-04 13:23:45.738 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/api/Clientes  
2021-08-04 13:23:45.738 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:45.739 -03:00 [INF] Route matched with {action = "Get", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:23:45.739 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Get (CL.WebApi) in 0.5152ms
2021-08-04 13:23:45.741 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Get (CL.WebApi)'
2021-08-04 13:23:45.741 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Error de teste
   at CL.WebApi.Controllers.ClientesController.Get() in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Controllers\ClientesController.cs:line 35
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-08-04 13:23:45.746 -03:00 [INF] Request finished in 7.8176ms 500 text/plain
2021-08-04 13:38:19.491 -03:00 [INF] Iniciando o WebApi
2021-08-04 13:38:21.051 -03:00 [INF] Entity Framework Core 5.0.8 initialized 'ClContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2021-08-04 13:38:29.562 -03:00 [INF] Executed DbCommand (139ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 13:38:29.726 -03:00 [INF] Executed DbCommand (144ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-08-04 13:38:29.737 -03:00 [INF] Executed DbCommand (7ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 13:38:29.740 -03:00 [INF] Executed DbCommand (2ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-08-04 13:38:29.794 -03:00 [INF] Executed DbCommand (13ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
2021-08-04 13:38:29.814 -03:00 [INF] No migrations were applied. The database is already up to date.
2021-08-04 13:38:29.817 -03:00 [INF] Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 13:38:30.067 -03:00 [INF] Executed DbCommand (247ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
2021-08-04 13:38:30.224 -03:00 [INF] Application started. Press Ctrl+C to shut down.
2021-08-04 13:38:30.225 -03:00 [INF] Hosting environment: Development
2021-08-04 13:38:30.225 -03:00 [INF] Content root path: C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi
2021-08-04 13:38:30.261 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/index.html  
2021-08-04 13:38:30.362 -03:00 [INF] Request finished in 104.9146ms 200 text/html;charset=utf-8
2021-08-04 13:38:30.815 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/swagger/v1/swagger.json  
2021-08-04 13:38:31.011 -03:00 [INF] Request finished in 196.7154ms 200 application/json;charset=utf-8
2021-08-04 13:39:02.090 -03:00 [INF] Request starting HTTP/2.0 POST https://localhost:44319/api/Clientes application/json 156
2021-08-04 13:39:02.128 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Post (CL.WebApi)'
2021-08-04 13:39:02.188 -03:00 [INF] Route matched with {action = "Post", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Post(CL.Core.Shared.ModelViews.NovoCliente) on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:39:02.532 -03:00 [INF] Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ValidationProblemDetails'.
2021-08-04 13:39:02.549 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Post (CL.WebApi) in 352.1538ms
2021-08-04 13:39:02.551 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Post (CL.WebApi)'
2021-08-04 13:39:02.553 -03:00 [INF] Request finished in 464.4121ms 400 application/problem+json; charset=utf-8
2021-08-04 13:40:01.159 -03:00 [INF] Request starting HTTP/2.0 POST https://localhost:44319/api/Clientes application/json 157
2021-08-04 13:40:01.160 -03:00 [INF] Executing endpoint 'CL.WebApi.Controllers.ClientesController.Post (CL.WebApi)'
2021-08-04 13:40:01.161 -03:00 [INF] Route matched with {action = "Post", controller = "Clientes"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Post(CL.Core.Shared.ModelViews.NovoCliente) on controller CL.WebApi.Controllers.ClientesController (CL.WebApi).
2021-08-04 13:40:01.170 -03:00 [INF] Foi requisitada a inserção de um novo cliente
2021-08-04 13:40:01.198 -03:00 [INF] Entity Framework Core 5.0.8 initialized 'ClContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2021-08-04 13:40:01.560 -03:00 [INF] Executed DbCommand (71ms) [Parameters=[@p0='?' (DbType = DateTime2), @p1='?' (DbType = DateTime2), @p2='?' (Size = 4000), @p3='?' (Size = 4000), @p4='?' (Size = 1), @p5='?' (Size = 4000), @p6='?' (DbType = DateTime2)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Clientes] ([Criacao], [DataNascimento], [Documento], [Nome_Cliente], [Sexo], [Telefone], [UltimaAtualizacao])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6);
SELECT [Id_Cliente]
FROM [Clientes]
WHERE @@ROWCOUNT = 1 AND [Id_Cliente] = scope_identity();
2021-08-04 13:40:01.619 -03:00 [INF] Executing ObjectResult, writing value of type 'CL.Core.Domain.Cliente'.
2021-08-04 13:40:01.656 -03:00 [INF] Executed action CL.WebApi.Controllers.ClientesController.Post (CL.WebApi) in 494.9273ms
2021-08-04 13:40:01.657 -03:00 [INF] Executed endpoint 'CL.WebApi.Controllers.ClientesController.Post (CL.WebApi)'
2021-08-04 13:40:01.661 -03:00 [INF] Request finished in 503.1342ms 201 application/json; charset=utf-8
2021-08-04 13:51:43.024 -03:00 [INF] Iniciando o WebApi
2021-08-04 13:51:44.053 -03:00 [FTL] Erro Catastrófico.
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: CL.Manager.Interfaces.IClienteManager Lifetime: Scoped ImplementationType: CL.Manager.Implementation.ClienteManager': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: CL.Manager.Interfaces.IClienteManager Lifetime: Scoped ImplementationType: CL.Manager.Implementation.ClienteManager': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CL.WebApi.Program.Main(String[] args) in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Program.cs:line 27
2021-08-04 13:52:46.121 -03:00 [INF] Iniciando o WebApi
2021-08-04 13:52:47.599 -03:00 [FTL] Erro Catastrófico.
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: CL.Manager.Interfaces.IClienteManager Lifetime: Scoped ImplementationType: CL.Manager.Implementation.ClienteManager': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: CL.Manager.Interfaces.IClienteManager Lifetime: Scoped ImplementationType: CL.Manager.Implementation.ClienteManager': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CL.WebApi.Program.Main(String[] args) in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Program.cs:line 27
2021-08-04 13:55:42.576 -03:00 [INF] Iniciando o WebApi
2021-08-04 13:55:43.115 -03:00 [FTL] Erro Catastrófico.
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: CL.Manager.Interfaces.IClienteManager Lifetime: Scoped ImplementationType: CL.Manager.Implementation.ClienteManager': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: CL.Manager.Interfaces.IClienteManager Lifetime: Scoped ImplementationType: CL.Manager.Implementation.ClienteManager': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CL.WebApi.Program.Main(String[] args) in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Program.cs:line 27
2021-08-04 14:02:10.717 -03:00 [INF] Iniciando o WebApi
2021-08-04 14:02:11.290 -03:00 [FTL] Erro Catastrófico.
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: CL.Manager.Interfaces.IClienteManager Lifetime: Scoped ImplementationType: CL.Manager.Implementation.ClienteManager': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: CL.Manager.Interfaces.IClienteManager Lifetime: Scoped ImplementationType: CL.Manager.Implementation.ClienteManager': Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'CL.Manager.Implementation.ClienteManager'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CL.WebApi.Program.Main(String[] args) in C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi\Program.cs:line 21
2021-08-04 14:03:59.120 -03:00 [INF] Iniciando o WebApi
2021-08-04 14:04:00.591 -03:00 [INF] Entity Framework Core 5.0.8 initialized 'ClContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2021-08-04 14:04:08.286 -03:00 [INF] Executed DbCommand (29ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:04:08.327 -03:00 [INF] Executed DbCommand (23ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-08-04 14:04:08.332 -03:00 [INF] Executed DbCommand (2ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:04:08.333 -03:00 [INF] Executed DbCommand (1ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-08-04 14:04:08.379 -03:00 [INF] Executed DbCommand (2ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
2021-08-04 14:04:08.406 -03:00 [INF] No migrations were applied. The database is already up to date.
2021-08-04 14:04:08.408 -03:00 [INF] Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:04:08.444 -03:00 [INF] Executed DbCommand (34ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
2021-08-04 14:04:08.727 -03:00 [INF] Application started. Press Ctrl+C to shut down.
2021-08-04 14:04:08.727 -03:00 [INF] Hosting environment: Development
2021-08-04 14:04:08.727 -03:00 [INF] Content root path: C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi
2021-08-04 14:04:08.800 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/index.html  
2021-08-04 14:04:08.973 -03:00 [INF] Request finished in 178.124ms 200 text/html;charset=utf-8
2021-08-04 14:04:09.240 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/swagger/v1/swagger.json  
2021-08-04 14:04:09.417 -03:00 [INF] Request finished in 176.715ms 200 application/json;charset=utf-8
2021-08-04 14:38:32.494 -03:00 [INF] Iniciando o WebApi
2021-08-04 14:38:32.915 -03:00 [DBG] Hosting starting
2021-08-04 14:38:33.064 -03:00 [DBG] An 'IServiceProvider' was created for internal use by Entity Framework.
2021-08-04 14:38:33.734 -03:00 [INF] Entity Framework Core 5.0.8 initialized 'ClContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2021-08-04 14:38:33.800 -03:00 [DBG] Migrating using database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:33.808 -03:00 [DBG] Opening connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.364 -03:00 [DBG] Opened connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.377 -03:00 [DBG] Creating DbCommand for 'ExecuteNonQuery'.
2021-08-04 14:38:39.391 -03:00 [DBG] Created DbCommand for 'ExecuteNonQuery' (9ms).
2021-08-04 14:38:39.409 -03:00 [DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:38:39.452 -03:00 [INF] Executed DbCommand (46ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:38:39.457 -03:00 [DBG] Closing connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.464 -03:00 [DBG] Closed connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.472 -03:00 [DBG] Creating DbCommand for 'ExecuteScalar'.
2021-08-04 14:38:39.472 -03:00 [DBG] Created DbCommand for 'ExecuteScalar' (0ms).
2021-08-04 14:38:39.472 -03:00 [DBG] Opening connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.474 -03:00 [DBG] Opened connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.475 -03:00 [DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-08-04 14:38:39.504 -03:00 [INF] Executed DbCommand (30ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-08-04 14:38:39.504 -03:00 [DBG] Closing connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.505 -03:00 [DBG] Closed connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.509 -03:00 [DBG] Opening connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.509 -03:00 [DBG] Opened connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.509 -03:00 [DBG] Creating DbCommand for 'ExecuteNonQuery'.
2021-08-04 14:38:39.509 -03:00 [DBG] Created DbCommand for 'ExecuteNonQuery' (0ms).
2021-08-04 14:38:39.509 -03:00 [DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:38:39.511 -03:00 [INF] Executed DbCommand (2ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:38:39.511 -03:00 [DBG] Closing connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.512 -03:00 [DBG] Closed connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.512 -03:00 [DBG] Creating DbCommand for 'ExecuteScalar'.
2021-08-04 14:38:39.512 -03:00 [DBG] Created DbCommand for 'ExecuteScalar' (0ms).
2021-08-04 14:38:39.512 -03:00 [DBG] Opening connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.512 -03:00 [DBG] Opened connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.512 -03:00 [DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-08-04 14:38:39.513 -03:00 [INF] Executed DbCommand (1ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-08-04 14:38:39.513 -03:00 [DBG] Closing connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.513 -03:00 [DBG] Closed connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.547 -03:00 [DBG] Creating DbCommand for 'ExecuteReader'.
2021-08-04 14:38:39.547 -03:00 [DBG] Created DbCommand for 'ExecuteReader' (0ms).
2021-08-04 14:38:39.547 -03:00 [DBG] Opening connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.547 -03:00 [DBG] Opened connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.548 -03:00 [DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
2021-08-04 14:38:39.553 -03:00 [INF] Executed DbCommand (5ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
2021-08-04 14:38:39.558 -03:00 [DBG] A data reader was disposed.
2021-08-04 14:38:39.558 -03:00 [DBG] Closing connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.558 -03:00 [DBG] Closed connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.581 -03:00 [INF] No migrations were applied. The database is already up to date.
2021-08-04 14:38:39.583 -03:00 [DBG] Opening connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.583 -03:00 [DBG] Opened connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.583 -03:00 [DBG] Creating DbCommand for 'ExecuteNonQuery'.
2021-08-04 14:38:39.583 -03:00 [DBG] Created DbCommand for 'ExecuteNonQuery' (0ms).
2021-08-04 14:38:39.583 -03:00 [DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:38:39.584 -03:00 [INF] Executed DbCommand (1ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-08-04 14:38:39.584 -03:00 [DBG] Closing connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.585 -03:00 [DBG] Closed connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.588 -03:00 [DBG] Creating DbCommand for 'ExecuteScalar'.
2021-08-04 14:38:39.588 -03:00 [DBG] Created DbCommand for 'ExecuteScalar' (0ms).
2021-08-04 14:38:39.588 -03:00 [DBG] Opening connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.589 -03:00 [DBG] Opened connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.589 -03:00 [DBG] Executing DbCommand [Parameters=[], CommandType='"Text"', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
2021-08-04 14:38:39.745 -03:00 [INF] Executed DbCommand (156ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
2021-08-04 14:38:39.746 -03:00 [DBG] Closing connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.746 -03:00 [DBG] Closed connection to database 'BD_Consultorio_Legal' on server '(localdb)\MSSQLLocalDB'.
2021-08-04 14:38:39.750 -03:00 [DBG] 'ClContext' disposed.
2021-08-04 14:38:39.875 -03:00 [DBG] Loaded hosting startup assembly CL.WebApi
2021-08-04 14:38:39.876 -03:00 [INF] Application started. Press Ctrl+C to shut down.
2021-08-04 14:38:39.876 -03:00 [INF] Hosting environment: Development
2021-08-04 14:38:39.877 -03:00 [INF] Content root path: C:\Users\vanessa.campioni\source\repos\Consultorio_Legal\CL.WebApi
2021-08-04 14:38:39.877 -03:00 [DBG] Hosting started
2021-08-04 14:38:39.922 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/index.html  
2021-08-04 14:38:39.925 -03:00 [DBG] Wildcard detected, all requests with hosts will be allowed.
2021-08-04 14:38:40.019 -03:00 [INF] Request finished in 104.0971ms 200 text/html;charset=utf-8
2021-08-04 14:38:40.377 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44319/swagger/v1/swagger.json  
2021-08-04 14:38:40.561 -03:00 [INF] Request finished in 184.0089ms 200 application/json;charset=utf-8
{"@t":"2021-08-04T20:46:37.1777505Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"System.Exception: Erro de teste\r\n   at CL.WebApi.Controllers.ClientesController.Get() in C:\\Users\\vanessa.campioni\\source\\repos\\Consultorio_Legal\\CL.WebApi\\Controllers\\ClientesController.cs:line 40\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"80000015-0006-ff00-b63f-84710c7967bb","RequestPath":"/api/Clientes","SpanId":"|bd0263fb-4169575d7eb284d2.","TraceId":"bd0263fb-4169575d7eb284d2","ParentId":""}
{"@t":"2021-08-04T20:56:23.3827847Z","@mt":"An unhandled exception has occurred while executing the request.","@l":"Error","@x":"System.Exception: Erro de teste\r\n   at CL.WebApi.Controllers.ClientesController.Get() in C:\\Users\\vanessa.campioni\\source\\repos\\Consultorio_Legal\\CL.WebApi\\Controllers\\ClientesController.cs:line 40\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)","EventId":{"Id":1,"Name":"UnhandledException"},"SourceContext":"Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware","RequestId":"80000037-0000-ff00-b63f-84710c7967bb","RequestPath":"/api/Clientes","SpanId":"|5366bca2-465b6f8e6698bf87.","TraceId":"5366bca2-465b6f8e6698bf87","ParentId":""}
